# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certs < Formula
  desc "Fast, local TLS scanning. Same engine as certs.lol."
  homepage "https://certs.lol"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.3.0/certs_darwin_amd64.tar.gz"
      sha256 "1d98f5b774964ace2244b9c06622ed88da9b98d4464beda96753aca332b4cd1f"

      define_method(:install) do
        bin.install "certs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.3.0/certs_darwin_arm64.tar.gz"
      sha256 "0e2b19d1d913d302ba338f72612510c01a8923ad4d492db4fd41eaa1e0fba148"

      define_method(:install) do
        bin.install "certs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.3.0/certs_linux_amd64.tar.gz"
      sha256 "90d51faa151a4c01637a2f76b405e9b913b3761f060afdd75a04bf77373af710"
      define_method(:install) do
        bin.install "certs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.3.0/certs_linux_arm64.tar.gz"
      sha256 "295323e5ee1087f33346e8a6b74eec29867acd7a46c55d77249ed82b66b0d7d4"
      define_method(:install) do
        bin.install "certs"
      end
    end
  end

  test do
    assert_match "certs", shell_output("#{bin}/certs version")
  end
end
