# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certs < Formula
  desc "Local TLS scanner — certs.lol from your terminal"
  homepage "https://certs.lol"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.0/certs_darwin_amd64.tar.gz"
      sha256 "1bfb61e2ce3650b93fe11d6c3364ada7d7923b7d5d7adbb8de84f65522e2048e"
    end
    on_arm do
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.0/certs_darwin_arm64.tar.gz"
      sha256 "33ca86854a89c410166a6d72f51b2c02534743bbfedb5123900b6834a13fac68"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.0/certs_linux_amd64.tar.gz"
      sha256 "25ef120affdcb09bbfa36abff909d41797c4cc719669450dde877192ddb3c21e"
    end
    on_arm do
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.0/certs_linux_arm64.tar.gz"
      sha256 "2b3ade2d872ae3bcf13fc7a299d03d6ef79dda42b4d256fccb4678c1265da07f"
    end
  end

  def install
    bin.install "certs"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/certs version")
  end
end
