# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certs < Formula
  desc "Fast, local TLS scanning. Same engine as certs.lol."
  homepage "https://certs.lol"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.2/certs_darwin_amd64.tar.gz"
      sha256 "2c24549c5487260b08c9a35b3eca15fbe6324d9437af18739474eb17b0f1d29c"

      define_method(:install) do
        bin.install "certs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.2/certs_darwin_arm64.tar.gz"
      sha256 "a399de6624b318f42a25f86cb558731f7bf2e7d6d535a03b607166214fd1acf4"

      define_method(:install) do
        bin.install "certs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.2/certs_linux_amd64.tar.gz"
      sha256 "725fb5933d99192495c397c33b7524be86b123a7aa60bfc15158c2117cd727b7"
      define_method(:install) do
        bin.install "certs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/certs-lol/releases/download/v1.0.2/certs_linux_arm64.tar.gz"
      sha256 "e869692379fdaa442126ecb8acb3ca5059090a4b8cb72ccc9a7d00aa3e213380"
      define_method(:install) do
        bin.install "certs"
      end
    end
  end

  test do
    assert_match "certs", shell_output("#{bin}/certs version")
  end
end
