# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ns < Formula
  desc "Fast, API-first DNS lookup. Same engine as ns.lol."
  homepage "https://ns.lol"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.1/ns_darwin_amd64.tar.gz"
      sha256 "06f8936c234b930c4769015a11819ee2c8b8c28b1c6a60bf25e451b2a00fa0fe"

      define_method(:install) do
        bin.install "ns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.1/ns_darwin_arm64.tar.gz"
      sha256 "821867a8fb6d7c1d097ff97d2716f4bc9dcff61fd8324fb2e62810a23ae78e7c"

      define_method(:install) do
        bin.install "ns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.1/ns_linux_amd64.tar.gz"
      sha256 "2275b533cf0aa5dd08a66455f964c88c267f91a0e652fc32d70ee2227bfc6907"
      define_method(:install) do
        bin.install "ns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.1/ns_linux_arm64.tar.gz"
      sha256 "c475d77db5460c93851e2e4ae55a52c43ccc00c0017aa2c705b356deb93cadc7"
      define_method(:install) do
        bin.install "ns"
      end
    end
  end

  test do
    assert_match "ns", shell_output("#{bin}/ns version")
  end
end
