# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ns < Formula
  desc "Fast, API-first DNS lookup. Same engine as ns.lol."
  homepage "https://ns.lol"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_darwin_amd64.tar.gz"
      sha256 "f52866de477fa4d9603e68d6e12922fe710d5cf815f5d15330de081fc0b0ce44"

      define_method(:install) do
        bin.install "ns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_darwin_arm64.tar.gz"
      sha256 "3399a997661059c2be3ef39dfb2b1b05e3e9560dd1a1d8b79308a3e4fa6495ff"

      define_method(:install) do
        bin.install "ns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_linux_amd64.tar.gz"
      sha256 "e7f80c0226e026f991a16fc93ca2540689f19b954b1162e1ebdf6db91061dd60"
      define_method(:install) do
        bin.install "ns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_linux_arm64.tar.gz"
      sha256 "1d58cd2c499ef35b5d2e3b6fc329fbc8502b4b28bd6dca6178615bfde0d2e2e8"
      define_method(:install) do
        bin.install "ns"
      end
    end
  end

  test do
    assert_match "ns", shell_output("#{bin}/ns version")
  end
end
