# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ns < Formula
  desc "Fast, API-first DNS lookup. Same engine as ns.lol."
  homepage "https://ns.lol"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_darwin_amd64.tar.gz"
      sha256 "db1366f7bc7573f04390aa5262c2ba7e2bf853d39068a74ba124f634f8183931"

      define_method(:install) do
        bin.install "ns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_darwin_arm64.tar.gz"
      sha256 "ee573d21bec88627070ddd08ac63d294df9da02ac1207cd93ffcab26934d59e6"

      define_method(:install) do
        bin.install "ns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_linux_amd64.tar.gz"
      sha256 "d65a0ec7d3d2383b495b8f7c47f3800072e350e561e65e6b6acd027a51b8c124"
      define_method(:install) do
        bin.install "ns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/ns-lol/releases/download/v0.1.0/ns_linux_arm64.tar.gz"
      sha256 "0e9d7114eb6d24be51707c0e11400a2a0ce43be452200aede3c4f546c26f3d51"
      define_method(:install) do
        bin.install "ns"
      end
    end
  end

  test do
    assert_match "ns", shell_output("#{bin}/ns version")
  end
end
