# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vrfy < Formula
  desc "Email validation — no SMTP probes, no API keys, proof-of-work anti-abuse"
  homepage "https://vrfy.lol"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/vrfy-lol/releases/download/v1.0.0/vrfy_darwin_amd64.tar.gz"
      sha256 "7f4b6006922cbe6939040f694ab0290470465598aa4939aebd9d99124a4816fd"

      define_method(:install) do
        bin.install "vrfy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/vrfy-lol/releases/download/v1.0.0/vrfy_darwin_arm64.tar.gz"
      sha256 "d73af35b359aae91c50812808cc95be0cb50c333e28e2be9d68b8d9012f4a83d"

      define_method(:install) do
        bin.install "vrfy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/vrfy-lol/releases/download/v1.0.0/vrfy_linux_amd64.tar.gz"
      sha256 "8dea3866bc3bc491b912eca505860a16faf2376b28a52c02bef150b267b356ec"
      define_method(:install) do
        bin.install "vrfy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/vrfy-lol/releases/download/v1.0.0/vrfy_linux_arm64.tar.gz"
      sha256 "742af195bd4b30507ef66c56a888db3807992faf0a176e7dcaa64931db553bb9"
      define_method(:install) do
        bin.install "vrfy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vrfy --version")
  end
end
