# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xhttp < Formula
  desc "HTTP response debugger — CORS, CSP, security headers, redirects, cache"
  homepage "https://xhttp.lol"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/xhttp/releases/download/v1.0.0/xhttp_darwin_amd64.tar.gz"
      sha256 "aecd0e0fed8ab17e664681e4f059eadfb7e14a520f0073a74649f67e3ece6096"

      define_method(:install) do
        bin.install "xhttp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/xhttp/releases/download/v1.0.0/xhttp_darwin_arm64.tar.gz"
      sha256 "cf4f54af8bac504546748abf5b2ee0463c420af4ba85129142b23940d30af2e8"

      define_method(:install) do
        bin.install "xhttp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/xhttp/releases/download/v1.0.0/xhttp_linux_amd64.tar.gz"
      sha256 "4c91377832ce0c7704b998764c900878c78e00b053258b10534aabc96060e346"
      define_method(:install) do
        bin.install "xhttp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/xhttp/releases/download/v1.0.0/xhttp_linux_arm64.tar.gz"
      sha256 "1e9a854aea2161de8b1a752edcfea2531d314a07c45133b5d0fb5c710309a6b7"
      define_method(:install) do
        bin.install "xhttp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xhttp version")
  end
end
