# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yoke < Formula
  desc "Domain intelligence in one pass — DNS, WHOIS, SSL, security, tech stack, performance, breaches, and AI analysis"
  homepage "https://yoke.lol"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.5.0/yoke_1.5.0_darwin_amd64.tar.gz"
      sha256 "2e1d00dceca8c8ba1c6e96f2a56930e7f27f0a1f5e9a78d6e02c980b7efb62bc"

      define_method(:install) do
        bin.install "yoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.5.0/yoke_1.5.0_darwin_arm64.tar.gz"
      sha256 "011d6bef27ea7a9d62e8f2dcdfdc3419644cd5b7814170b033a82647f059e153"

      define_method(:install) do
        bin.install "yoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.5.0/yoke_1.5.0_linux_amd64.tar.gz"
      sha256 "3175f7827adacb80347b20ab39a70f143843c40aa3cbf363606d6021aab3884a"
      define_method(:install) do
        bin.install "yoke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.5.0/yoke_1.5.0_linux_arm64.tar.gz"
      sha256 "b417f4ccc6a45b5db97cb14ade5d65adc877193343178a7f49a7e2d1cc83f748"
      define_method(:install) do
        bin.install "yoke"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/yoke --version")
  end
end
