# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yoke < Formula
  desc "Domain intelligence in one pass — DNS, WHOIS, SSL, security, tech stack, performance, breaches, and AI analysis"
  homepage "https://yoke.lol"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.6.0/yoke_1.6.0_darwin_amd64.tar.gz"
      sha256 "b30c0ed1dfa74e4ae8e79b4335498cb867f37025b04ca2d2a84f39c3f83c5f10"

      define_method(:install) do
        bin.install "yoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.6.0/yoke_1.6.0_darwin_arm64.tar.gz"
      sha256 "ff24fc2074aeb4b1ff14b25f18cd8c38080dcfe0cfdf02381255f98b34b1a6ff"

      define_method(:install) do
        bin.install "yoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.6.0/yoke_1.6.0_linux_amd64.tar.gz"
      sha256 "0dbf085b25a7a063ee2eb014f05df0a0ba1257877388a4ac3c72961b3481d4dc"
      define_method(:install) do
        bin.install "yoke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.6.0/yoke_1.6.0_linux_arm64.tar.gz"
      sha256 "01532230cd6595ec611eb883a4ddf27d39e450efd85632f7116c7292ba5edd1c"
      define_method(:install) do
        bin.install "yoke"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/yoke --version")
  end
end
