# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yoke < Formula
  desc "Domain intelligence in one pass — DNS, WHOIS, SSL, security, tech stack, performance, breaches, and AI analysis"
  homepage "https://yoke.lol"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.4.0/yoke_1.4.0_darwin_amd64.tar.gz"
      sha256 "69bd6f078dec74cd073ddf7445da80c93141a1c4ce55e88ff218cb4d8c8b95f7"

      define_method(:install) do
        bin.install "yoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.4.0/yoke_1.4.0_darwin_arm64.tar.gz"
      sha256 "4b67977905fb778e1b7ef99ce10f206c978237832bfff0f1fb19466097a49a72"

      define_method(:install) do
        bin.install "yoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.4.0/yoke_1.4.0_linux_amd64.tar.gz"
      sha256 "a28474f9ae189bfc0e653722238f34088050dfb6b48262c115e058df1140acdc"
      define_method(:install) do
        bin.install "yoke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yokedotlol/yoke/releases/download/v1.4.0/yoke_1.4.0_linux_arm64.tar.gz"
      sha256 "a5c6bbea7539df2b5b4aaaf6b33f876a6584d9a20688e0a9f4940757d10dd912"
      define_method(:install) do
        bin.install "yoke"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/yoke --version")
  end
end
